export const APP_CART = "APP_CART"; //Загрудить товар с сервера
export const TOTAL = "TOTAL"; //Подсчет общей цены
export const DELETE_ITEM = "DELETE_ITEM"; //Удаляем товар из корзины
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'; //Изменение количества товара
export const MAIL_INPUT = 'MAIL_INPUT'; //Ввод Email
export const ENTER_ADDRESS = 'ENTER_ADDRESS'; //Ввод адреса
export const PHONE_INPUT = 'PHONE_INPUT'; //Ввод НОМЕРА ТЕЛЕФОНА
export const NAME_INPUT = 'NAME_INPUT'; //Ввод Имени
export const VALID_EMAIL = 'VALID_EMAIL'; //проверка Email
export const ADD_MESSAGE = 'ADD_MESSAGE'; //Добавление сообщения
export const VALID_NAME = 'VALID_NAME'; //Проверка имени
export const VALID_ADDRESS = 'VALID_ADDRESS'; //Проверка адресса
export const VALID_PHONE = 'VALID_PHONE'; //Проверка номера телефона
export const SECTION_SELECTION = 'SECTION_SELECTION'; //Выбор селектора в выпадающем списке
export const OPEN_CLOSE = 'OPEN/CLOSE'; //открыть/закрыть выпадающий список
export const PRIVILEGE = 'PRIVILEGE' ; //Если общая цена заказа больше 300 евро, в список выбора цены за доставку вносим "Free express shipping"
export const APP_KEY = 'APP_KEY'; //Добавляем способ доставки по умолчанию
export const CLEANING = 'CLEANING'; //очистка формы после отправки